### ISSUE TITLE
import html

### ISSUE THREAD

**Issue by stevenvachon** [matthewp/views-the-hard-way#1]
This eases the hard way a bit for easier maintenance of _source_ code:
```js
import innerHTML from './template.html';

document.createElement('template').innerHTML = innerHTML;
```

The built file could be the released file.

**Comment by matthewp** [comment]
Yeah, sure, when we have HTML module imports like that it surely will be a good idea!

**Comment by matthewp** [comment]
Ah, I just realized that you're making a suggestion to build a view out of parts. Hm, I'll have to think about that. I think once I've finished documenting the method it might be worth going into strategies for better maintenance and this could be one of them.

**Comment by matthewp** [comment]
HTML modules still seem pretty far away unfortunately. Maybe some day!
